In [20]:
import pandas as pd

df = pd.read_csv('bond.csv')
df.set_index('Film',inplace=True)
df.sort_index(inplace=True)
df.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [7]:

df.loc['Diamonds Are Forever':'Moonraker']

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN

In [10]:
mask = df['Box Office']==df['Box Office'].min()
df[mask]

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9

In [21]:
df.reset_index(inplace=True)
df

,Film,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
0,A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
1,Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
2,Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
3,Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
4,Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
5,Dr. No,1962,Sean Connery,Terence Young,448.8,7.0,0.6
6,For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
7,From Russia with Love,1963,Sean Connery,Terence Young,543.8,12.6,1.6
8,GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
9,Goldfinger,1964,Sean Connery,Guy Hamilton,820.4,18.6,3.2
10,Licence to Kill,1989,Timothy Dalton,John Glen,250.9,56.7,7.9
11,Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3,30.8,NaN
12,Moonraker,1979,Roger Moore,Lewis Gilbert,535.0,91.5,NaN
13,Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0,86.0,NaN
14,Octopussy,1983,Roger Moore,John Glen,373.8,53.9,7.8
15,On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5,37.3,0.6
16,Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2,181.4,8.1
17,Skyfall,2012,Daniel Craig,Sam Mendes,943.5,170.2,14.5
18,Spectre,2015,Daniel Craig,Sam Mendes,726.7,206.3,NaN
19,The Living Daylights,1987,Timothy Dalton,John Glen,313.5,68.8,5.2
20,The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0,27.7,NaN
21,The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0,45.1,NaN
22,The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5,158.3,13.5
23,Thunderball,1965,Sean Connery,Terence Young,848.1,41.9,4.7
24,Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2,133.9,10.0
25,You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [24]:
df.loc['Sean Connery']

KeyError: 'Sean Connery'