In [6]:
import pandas as pd

bond = pd.read_csv('bond.csv',index_col='Film')
bond.sort_index(inplace=True)

In [27]:
mask = bond['Actor'] == 'Sir Sean Connery'
#bond.loc[mask,'Actor'] = 'Sir Sean Connery'
bond.ix[mask]

c:\users\sumit\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:3: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2
Never Say Never Again,1983,Sir Sean Connery,Irvin Kershner,380.0,86.0,NaN
Thunderball,1965,Sir Sean Connery,Terence Young,848.1,41.9,4.7
You Only Live Twice,1967,Sir Sean Connery,Lewis Gilbert,514.2,59.9,4.4

In [26]:
bond.head(10)

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sir Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9
Dr. No,1962,Sir Sean Connery,Terence Young,448.8,7.0,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4,60.2,NaN
From Russia with Love,1963,Sir Sean Connery,Terence Young,543.8,12.6,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5,76.9,5.1
Goldfinger,1964,Sir Sean Connery,Guy Hamilton,820.4,18.6,3.2

In [11]:
bond.loc['A View to a Kill','Actor']
bond.loc['A View to a Kill','Director']
bond.loc['A View to a Kill','Actor':'Budget']
bond.loc['A View to a Kill',['Year','Actor','Director','Budget']]

Year               1985
Actor       Roger Moore
Director      John Glen
Budget             54.5
Name: A View to a Kill, dtype: object